# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
  boot.kernel.sysctl = { "vm.swappiness" = 10; };

  fileSystems."/ssd" =
    {
      device = "/dev/disk/by-uuid/026c76bc-1279-459e-8e63-7b44ca8158db";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/D9DD-3F47";
      fsType = "vfat";
    };

  #fileSystems."/mediastorage" = {
  #  device = "/dev/disk/by-uuid/aed202ac-7414-40b9-9d71-011b7043c850";
  #  fsType = "ext4";
  #};

  fileSystems."/backups" = {
    device = "/dev/disk/by-uuid/63db910e-f906-4211-bac5-4330777c8283";
    fsType = "ext4";
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/7246a5a1-f5e9-44a0-9756-96c0571e3986";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };
    "/home" = {
      device = "/dev/disk/by-uuid/7246a5a1-f5e9-44a0-9756-96c0571e3986";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };
    "/nix" = {
      device = "/dev/disk/by-uuid/7246a5a1-f5e9-44a0-9756-96c0571e3986";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };
    "/var/lib/docker" = {
      device = "/dev/disk/by-uuid/7246a5a1-f5e9-44a0-9756-96c0571e3986";
      fsType = "btrfs";
      options = [ "subvol=docker" "compress=zstd" "noatime" ];
    };
  };

  swapDevices =
    [
     # { device = "/dev/disk/by-uuid/27f0bffa-7705-40c4-af59-e2bd3e2e9f9d"; }
    ];

}
